name: primeira-pipeline
on:
  push:
    branchs:["main"]
  workflow_dispatch:
jobs:
  primeiro-job:
    name:"meu primeiro job"
    runs-on: ubuntu-latest
    steps:
      - name:"Minha primeira acao"
        run: echo "hello world"
      - name: "Segunda acao"
        run: 
          echo "voce criou a primeira pipeline"
          echo "parabens"
      
      
